// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201218034235_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "description for product 1",
                            Name = "prodct 1",
                            Price = 871m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "description for product 2",
                            Name = "prodct 2",
                            Price = 821m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "description for product 3",
                            Name = "prodct 3",
                            Price = 424m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "description for product 4",
                            Name = "prodct 4",
                            Price = 612m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "description for product 5",
                            Name = "prodct 5",
                            Price = 358m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "description for product 6",
                            Name = "prodct 6",
                            Price = 153m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "description for product 7",
                            Name = "prodct 7",
                            Price = 458m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "description for product 8",
                            Name = "prodct 8",
                            Price = 682m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "description for product 9",
                            Name = "prodct 9",
                            Price = 800m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "description for product 10",
                            Name = "prodct 10",
                            Price = 591m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "description for product 11",
                            Name = "prodct 11",
                            Price = 492m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "description for product 12",
                            Name = "prodct 12",
                            Price = 559m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "description for product 13",
                            Name = "prodct 13",
                            Price = 957m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "description for product 14",
                            Name = "prodct 14",
                            Price = 868m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "description for product 15",
                            Name = "prodct 15",
                            Price = 868m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "description for product 16",
                            Name = "prodct 16",
                            Price = 170m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "description for product 17",
                            Name = "prodct 17",
                            Price = 612m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "description for product 18",
                            Name = "prodct 18",
                            Price = 949m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "description for product 19",
                            Name = "prodct 19",
                            Price = 304m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "description for product 20",
                            Name = "prodct 20",
                            Price = 865m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "description for product 21",
                            Name = "prodct 21",
                            Price = 839m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "description for product 22",
                            Name = "prodct 22",
                            Price = 935m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "description for product 23",
                            Name = "prodct 23",
                            Price = 323m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "description for product 24",
                            Name = "prodct 24",
                            Price = 818m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "description for product 25",
                            Name = "prodct 25",
                            Price = 619m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "description for product 26",
                            Name = "prodct 26",
                            Price = 721m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "description for product 27",
                            Name = "prodct 27",
                            Price = 219m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "description for product 28",
                            Name = "prodct 28",
                            Price = 630m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "description for product 29",
                            Name = "prodct 29",
                            Price = 445m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "description for product 30",
                            Name = "prodct 30",
                            Price = 266m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "description for product 31",
                            Name = "prodct 31",
                            Price = 668m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "description for product 32",
                            Name = "prodct 32",
                            Price = 890m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "description for product 33",
                            Name = "prodct 33",
                            Price = 774m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "description for product 34",
                            Name = "prodct 34",
                            Price = 809m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "description for product 35",
                            Name = "prodct 35",
                            Price = 429m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "description for product 36",
                            Name = "prodct 36",
                            Price = 714m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "description for product 37",
                            Name = "prodct 37",
                            Price = 816m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "description for product 38",
                            Name = "prodct 38",
                            Price = 441m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "description for product 39",
                            Name = "prodct 39",
                            Price = 914m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "description for product 40",
                            Name = "prodct 40",
                            Price = 751m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "description for product 41",
                            Name = "prodct 41",
                            Price = 794m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "description for product 42",
                            Name = "prodct 42",
                            Price = 459m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "description for product 43",
                            Name = "prodct 43",
                            Price = 420m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "description for product 44",
                            Name = "prodct 44",
                            Price = 412m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "description for product 45",
                            Name = "prodct 45",
                            Price = 688m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "description for product 46",
                            Name = "prodct 46",
                            Price = 366m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "description for product 47",
                            Name = "prodct 47",
                            Price = 533m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "description for product 48",
                            Name = "prodct 48",
                            Price = 794m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "description for product 49",
                            Name = "prodct 49",
                            Price = 311m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "description for product 50",
                            Name = "prodct 50",
                            Price = 411m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "description for product 51",
                            Name = "prodct 51",
                            Price = 652m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "description for product 52",
                            Name = "prodct 52",
                            Price = 375m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "description for product 53",
                            Name = "prodct 53",
                            Price = 590m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "description for product 54",
                            Name = "prodct 54",
                            Price = 603m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "description for product 55",
                            Name = "prodct 55",
                            Price = 757m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "description for product 56",
                            Name = "prodct 56",
                            Price = 935m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "description for product 57",
                            Name = "prodct 57",
                            Price = 598m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "description for product 58",
                            Name = "prodct 58",
                            Price = 606m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "description for product 59",
                            Name = "prodct 59",
                            Price = 992m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "description for product 60",
                            Name = "prodct 60",
                            Price = 637m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "description for product 61",
                            Name = "prodct 61",
                            Price = 933m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "description for product 62",
                            Name = "prodct 62",
                            Price = 828m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "description for product 63",
                            Name = "prodct 63",
                            Price = 337m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "description for product 64",
                            Name = "prodct 64",
                            Price = 633m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "description for product 65",
                            Name = "prodct 65",
                            Price = 923m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "description for product 66",
                            Name = "prodct 66",
                            Price = 602m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "description for product 67",
                            Name = "prodct 67",
                            Price = 784m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "description for product 68",
                            Name = "prodct 68",
                            Price = 248m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "description for product 69",
                            Name = "prodct 69",
                            Price = 539m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "description for product 70",
                            Name = "prodct 70",
                            Price = 254m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "description for product 71",
                            Name = "prodct 71",
                            Price = 353m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "description for product 72",
                            Name = "prodct 72",
                            Price = 271m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "description for product 73",
                            Name = "prodct 73",
                            Price = 135m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "description for product 74",
                            Name = "prodct 74",
                            Price = 552m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "description for product 75",
                            Name = "prodct 75",
                            Price = 171m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "description for product 76",
                            Name = "prodct 76",
                            Price = 480m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "description for product 77",
                            Name = "prodct 77",
                            Price = 614m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "description for product 78",
                            Name = "prodct 78",
                            Price = 910m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "description for product 79",
                            Name = "prodct 79",
                            Price = 229m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "description for product 80",
                            Name = "prodct 80",
                            Price = 353m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "description for product 81",
                            Name = "prodct 81",
                            Price = 288m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "description for product 82",
                            Name = "prodct 82",
                            Price = 425m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "description for product 83",
                            Name = "prodct 83",
                            Price = 418m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "description for product 84",
                            Name = "prodct 84",
                            Price = 133m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "description for product 85",
                            Name = "prodct 85",
                            Price = 614m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "description for product 86",
                            Name = "prodct 86",
                            Price = 392m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "description for product 87",
                            Name = "prodct 87",
                            Price = 399m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "description for product 88",
                            Name = "prodct 88",
                            Price = 271m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "description for product 89",
                            Name = "prodct 89",
                            Price = 151m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "description for product 90",
                            Name = "prodct 90",
                            Price = 493m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "description for product 91",
                            Name = "prodct 91",
                            Price = 215m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "description for product 92",
                            Name = "prodct 92",
                            Price = 309m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "description for product 93",
                            Name = "prodct 93",
                            Price = 449m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "description for product 94",
                            Name = "prodct 94",
                            Price = 377m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "description for product 95",
                            Name = "prodct 95",
                            Price = 817m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "description for product 96",
                            Name = "prodct 96",
                            Price = 965m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "description for product 97",
                            Name = "prodct 97",
                            Price = 222m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "description for product 98",
                            Name = "prodct 98",
                            Price = 786m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "description for product 99",
                            Name = "prodct 99",
                            Price = 489m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "description for product 100",
                            Name = "prodct 100",
                            Price = 186m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("productinStocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 99
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 58
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 76
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 76
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 95
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 58
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 76
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 70
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 47
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 76
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 70
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 76
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
